@cbrown/1191 refactor gitea
StatCan/aaw-argocd-manifests pull request #150
Opened 2022-07-20 21:21 UTC by Collinbrown95

Add json 6902 patches for required istio annotations to allow traffic to postgres database in init container. Part of the solution to https://github.com/StatCan/daaas/issues/1191.

Add initial README.md content

2022-07-20 21:39 UTC, cboin1996 requested changes
Almost LGTM, I think you need to update the `securityContext` of the init container as per point 1 in issue https://github.com/StatCan/daaas/issues/1191. 
Referring to the upstream helm chart for gitea, I found https://gitea.com/gitea/helm-chart/src/tag/v5.0.4/values.yaml#L22 as a way to configure `securityContext` globally for all containers. I dont think this is what you would want however, so I propose a kustomize patch to change the `securityContext` to `1337` in the manifest [here](https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/profiles-argocd-system/template/gitea/protected-b/manifest.yaml#L421)

2022-07-20 21:39 UTC, cboin1996 commented on daaas-system/README.md
> +The primary tool used for AAW deployments is [ArgoCD]().
Are you missing a link to argocd here?

2022-07-20 21:44 UTC, Collinbrown95 commented on daaas-system/README.md
> +The primary tool used for AAW deployments is [ArgoCD]().
Good catch re: `securityContext`! I forgot to add this. The latter is what we want here (i.e. update the `securityContext` just for the `configure-gitea` init container).

Also yes - I was just going to link to https://argo-cd.readthedocs.io/en/stable/ (for readers who don't know our deployment infrastructure).

2022-07-21 16:06 UTC, cboin1996 approved these changes
Lgtm

2022-07-21 21:28 UTC, merged